### ISSUE TITLE
multiconvolve does not use samples after index 255

### ISSUE THREAD

**Issue by fhchl** [HISSTools/HISSTools_Impulse_Response_Toolbox#3]
There might be a bug in `multiconvolve` where samples after index 255 are not used in the convolution.

Appended is an example patch including to impulse responses ([multiconvolve_bug.zip](https://github.com/HISSTools/HISSTools_Impulse_Response_Toolbox/files/3857985/multiconvolve_bug.zip)). h255 has a single 1 at index 255. Convolution with that works as expected. h256 has single 1 at index 256. There is no output from `multiconvolve` with that response.

Interestingly, when "drawing" samples in waveform~ samples after 255 are taken into account as expected. 

Or might I do something wrong?

Tested with
HISSTools 1.1
Max 7.3.6 or Max 8.1.0
OS X 10.14.5

**Comment by AlexHarker** [comment]
Thanks for the report, but I believe this is fixed (not in the version you are using though). The bug I am aware of is more correctly described as some missing samples when the signal vector size >=256 - the exact set of missing samples depends on the vector size, but I believe they will always be between 256-1024) - the fix is in commit 83f0404f63267bb6ca8dd7fb2daac39a985b6b26.

Please download the new package release and confirm that the bug is now fixed:

https://cycling74.com/articles/package-arrival-the-hisstools-impulse-response-toolbox

Thanks

Alex

**Comment by fhchl** [comment]
The update to 2.0.1 fixed the issue. 🎉 

I was not aware that there is a 2.0 version out. A pointer to Max's Package Manager in the readme file might be helpful.

**Comment by AlexHarker** [comment]
Good. The package only just came out but this is a good idea. I've added something to the readme.

Thanks
